import { StyleSheet } from 'react-native';

// Styles converted from task-details.css for React Native compatibility
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    // paddingBottom:20,
    
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    // padding: 10,
    paddingTop: 10,
    paddingBottom: 30,
    paddingHorizontal: 10,
    backgroundColor: '#f6f3f3ff',
  },
  backButton: {
    marginRight: 16,
    top:18,
    padding: 8,
  },
  headerText: {
    // flex: 1,
    top:18,
    right:10,
  },
  taskId: {
    fontSize: 25,
    fontWeight: '700',
    color: '#11181C',
    // marginBottom: 20,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 15,
    color: '#070707ff',
    fontWeight: '400',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    top:50,
    // paddingBottom: 24,
    
  },
  card: {
    // bottom:10,
    backgroundColor: '#F5F5F5',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,

  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
  },
  statusDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  priorityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
  },
  priorityText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  section: {
    marginBottom: 28,
  },
  sectionHeader: {
    top: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 14,
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFF4F0',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#11181C',
    letterSpacing: 0.2,
  },
  sectionValue: {
    fontSize: 19,
    fontWeight: '700',
    color: '#11181C',
    marginBottom: 6,
    marginLeft: 58,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  sectionSubValue: {
    fontSize: 15,
    color: '#666666',
    marginLeft: 58,
    lineHeight: 20,
  },
  mapsButton: {
    backgroundColor: '#297dfbff',
    borderRadius: 14,
    padding: 18,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    gap: 10,
    shadowColor: '#0066FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 5,
  },
  startWorkButton: {
    backgroundColor: '#fbe14bff',
    borderRadius: 14,
    padding: 18,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 10,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 5,
  },
  buttonText1: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  buttonText2: {
    color: '#000',
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  underline1:{
    top:1,
    // paddingBottom:5,
    backgroundColor:"black",
    width:'full',
    // height:0.1,
    alignItems:'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  }
});

export default styles;
