import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const scale = width / 375; // base width for scaling
const verticalScale = height / 812; // base height for scaling

const responsiveSize = (size) => Math.round(size * scale);
const responsiveVertical = (size) => Math.round(size * verticalScale);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: responsiveVertical(10),
    paddingBottom: responsiveVertical(25),
    paddingHorizontal: responsiveSize(10),
    backgroundColor: '#f6f3f3ff',
  },
  backButton: {
    marginRight: responsiveSize(16),
    top: responsiveVertical(18),
    padding: responsiveSize(8),
  },
  headerText: {
    top: responsiveVertical(18),
    right: responsiveSize(10),
  },
  taskId: {
    fontSize: responsiveSize(25),
    fontWeight: '700',
    color: '#11181C',
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: responsiveSize(15),
    color: '#070707ff',
    fontWeight: '400',
  },
  content: {
    flex: 1,
    paddingHorizontal: responsiveSize(20),
    top: responsiveVertical(10),
  },
  card: {
    backgroundColor: '#F5F5F5',
    borderRadius: responsiveSize(20),
    padding: responsiveSize(24),
    marginBottom: responsiveVertical(24),
    borderWidth: 1,
    borderColor: '#E8E8E8',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: responsiveVertical(28),
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveSize(14),
    paddingVertical: responsiveVertical(8),
    borderRadius: responsiveSize(20),
    gap: responsiveSize(8),
  },
  statusDot: {
    width: responsiveSize(9),
    height: responsiveSize(9),
    borderRadius: responsiveSize(4.5),
  },
  statusText: {
    fontSize: responsiveSize(14),
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  priorityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveSize(14),
    paddingVertical: responsiveVertical(8),
    borderRadius: responsiveSize(20),
    gap: responsiveSize(8),
  },
  priorityText: {
    fontSize: responsiveSize(14),
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  section: {
    paddingTop: responsiveVertical(10),
  },
  sectionHeader: {
    top: responsiveVertical(20),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: responsiveVertical(10),
    gap: responsiveSize(14),
  },
  iconCircle: {
    width: responsiveSize(44),
    height: responsiveSize(44),
    borderRadius: responsiveSize(22),
    bottom: responsiveVertical(45),
    backgroundColor: '#FFF4F0',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionLabel: {
    fontSize: responsiveSize(16),
    fontWeight: '600',
    bottom: responsiveVertical(50),
    color: '#11181C',
    letterSpacing: 0.2,
  },
  sectionValue: {
    fontSize: responsiveSize(19),
    fontWeight: '700',
    color: '#11181C',
    bottom: responsiveVertical(30),
    paddingBottom: responsiveVertical(10),
    marginLeft: responsiveSize(58),
    letterSpacing: -0.3,
    lineHeight: responsiveVertical(26),
  },
  sectionSubValue: {
    fontSize: responsiveSize(15),
    color: '#666666',
    marginLeft: responsiveSize(58),
    bottom: responsiveVertical(113),
    lineHeight: responsiveVertical(20),
  },
  mapsButton: {
    backgroundColor: '#297dfbff',
    borderRadius: responsiveSize(14),
    padding: responsiveVertical(15),
    paddingHorizontal: responsiveSize(24),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: responsiveVertical(14),
    gap: responsiveSize(2),
    shadowColor: '#0066FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 5,
    bottom: responsiveVertical(15),
  },
  startWorkButton: {
    backgroundColor: '#fbe14bff',
    borderRadius: responsiveSize(14),
    padding: responsiveVertical(15),
    paddingHorizontal: responsiveSize(24),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: responsiveVertical(24),
    gap: responsiveSize(2),
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 5,
    bottom: responsiveVertical(15),
  },
  buttonText1: {
    color: '#fff',
    fontSize: responsiveSize(17),
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  buttonText2: {
    color: '#000',
    fontSize: responsiveSize(17),
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  underline1: {
    top: responsiveVertical(1),
    backgroundColor: 'black',
    width: '100%',
    alignItems: 'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
});

export default styles;
